"""initial schema

Revision ID: a3afb58af752
Revises: 
Create Date: 2025-08-11 15:24:46.121713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a3afb58af752'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=255), nullable=True),
    sa.Column('genres', mysql.JSON(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('averageRuntime', sa.Integer(), nullable=True),
    sa.Column('premiered', sa.String(length=255), nullable=True),
    sa.Column('ended', sa.String(length=255), nullable=True),
    sa.Column('officialSite', sa.String(length=255), nullable=True),
    sa.Column('schedule', mysql.JSON(), nullable=True),
    sa.Column('rating', mysql.JSON(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('network', mysql.JSON(), nullable=True),
    sa.Column('webchannel', mysql.JSON(), nullable=True),
    sa.Column('dvdCountry', mysql.JSON(), nullable=True),
    sa.Column('externals', mysql.JSON(), nullable=True),
    sa.Column('image', mysql.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('updated', sa.Integer(), nullable=True),
    sa.Column('_links', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('airdate', sa.String(length=50), nullable=True),
    sa.Column('airtime', sa.String(length=50), nullable=True),
    sa.Column('airstamp', sa.String(length=255), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('rating', mysql.JSON(), nullable=True),
    sa.Column('image', mysql.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('_links', mysql.JSON(), nullable=True),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('episodeOrder', sa.Integer(), nullable=True),
    sa.Column('premiereDate', sa.Text(), nullable=True),
    sa.Column('endDate', sa.Text(), nullable=True),
    sa.Column('network', mysql.JSON(), nullable=True),
    sa.Column('webchannel', mysql.JSON(), nullable=True),
    sa.Column('image', mysql.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('_links', mysql.JSON(), nullable=True),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seasons')
    op.drop_table('episodes')
    op.drop_table('shows')
    # ### end Alembic commands ###
